################################################################################
# RPKG Default configuration File                                              #
# Please edit as you see fit.                                                  #
################################################################################

# The version of LFS you are performing
VERSION="13.0"

# Backwards compatibility boolean (1 = True, 0 = False)
# Will your LFS install be using SystemD or SysV for the init system?
SYSTEMD=1

# Where the packages will be downloaded to
DIR="/mnt/lfs/sources/"

# How long the download speed tests should take before timing out
TIMEOUT=10

# How long the downloads of every package should take before timing out
MAX_TIMEOUT=300

# The list of repositories to use
REPOSITORIES="mirrorlist"

# Checksums file
MD5SUMS="md5sums"
